### ISSUE TITLE
疑似错字

### ISSUE THREAD

**Issue by NightFurySL2001** [LingDong-/qiji-font#12]
![image](https://user-images.githubusercontent.com/33471049/75013352-0d7cf080-54bf-11ea-948f-49aabdf54d03.png)

**Comment by NightFurySL2001** [comment]
Also please add a space. 🤣 Maybe copy the full-width space over to half-width space.
![image](https://user-images.githubusercontent.com/33471049/75013805-f8ed2800-54bf-11ea-9fe4-7ed0d9b9ead4.png)

**Comment by LingDong-** [comment]
Hi, thanks for pointing these out!

- I'm using less-common variant forms to generate those more often used characters. 𥿉(U+25FC9) is a variant form of 襪 and 袜 https://www.zdic.net/hans/𥿉.  Since there are currently no glyphs for 襪 and 袜, I'm filling them in with 𥿉. All the mapping rules can be found in `data/variant_map.txt`.

- Similarly 襍 is a variant form of 雜. https://www.zdic.net/hans/襍. However I didn't deliberately add it (雜 has its own glyph), it's more likely due to an error in the process. Will remove it.

- 祗 and 褸 are probably caused by OCR errors, I'll fix that. 

- I'll add both the ideographic space (U+3000) and space (U+0020).

Thanks again for spotting these errors.

**Comment by NightFurySL2001** [comment]
祗 can be match with 𥿄（糸氐，U+25FC4） or its variant 纸 (has its own character already)？

**Comment by NightFurySL2001** [comment]
![image](https://user-images.githubusercontent.com/33471049/75081950-46af7200-554c-11ea-8467-bf111346e243.png)

**Comment by LingDong-** [comment]
紙 has its own glyph while 祗 doesn't, so I'll need to make 祗 fallback.

Though by dictionary 朿 ≠ 束, it appeared in my original source (李長吉歌詩) as 束: 腸攢非束竹。胘急是張弓. So I guess that's kinda okay? 😂. Factually It is caused by OCR error though. There is a real, more correct 束 in the other source I was using (淮南鴻烈), so I'll switch 束 to that one and keep 朿 for, well, 朿.

![Snip20200221_2](https://user-images.githubusercontent.com/7929704/75084769-76309100-54f0-11ea-8b6a-feb7f617a479.png)

Thanks for finding these errors!

**Comment by NightFurySL2001** [comment]
Well current 朿 is from SHSerif so you may want to copy the glyph over from 束. Also I'm Chinese too so no worries :3

**Comment by LingDong-** [comment]
Hi @NightFurySL2001 ,

Now fixed:

- 朿->束, while 束 gets its own glyph
- 祗 褸 襍 removed
- spaces (0x20, 0x3000) added

Downloads on the release page is updated 🚀.

**Comment by NightFurySL2001** [comment]
Issue fixed. Thanks for quick response!
![image](https://user-images.githubusercontent.com/33471049/75443229-eb421180-599b-11ea-86d6-b1ea702d0b35.png)
