### ISSUE TITLE
Missing radical component (走之旁) in the character 【違】

### ISSUE THREAD

**Issue by tmin1986** [LingDong-/qiji-font#31]
The bottom part of the radical component 走之旁 in the character 【違】 is missing.

![Screen Shot 2021-08-22 at 00 10 43](https://user-images.githubusercontent.com/89309778/130326311-c7f70ff7-552e-42de-b420-50290a84619e.png)

**Comment by LingDong-** [comment]
Hi! Thanks a lot for reporting this issue! I just fixed it in the newest release: https://github.com/LingDong-/qiji-font/releases/tag/0.0.4

It is fixed by using another instance of the character in the source that's, well, not missing any parts :)

![image](https://user-images.githubusercontent.com/7929704/130338509-ff27dfb4-6d59-4dd1-9a59-9e672cb47348.png)

**Comment by tmin1986** [comment]
Thanks! :D
